import { version } from '/constants/version.js';
export async function loadGameplayModules() {
  const { DifficultyModel } = await import(`../models/DifficultyModel.min.js?${version}`);
  const { GradeModel } = await import(`../models/GradeModel.min.js?${version}`);
  const { StageModel } = await import(`../models/StageModel.min.js?${version}`);
  const { SetModel } = await import(`../models/SetModel.min.js?${version}`);
  const { CampaignModel } = await import(`../models/CampaignModel.min.js?${version}`);
  const { ResultModel } = await import(`../models/ResultModel.min.js?${version}`);
  const { YesNoModel } = await import(`../models/YesNoModel.min.js?${version}`);

  const grades = [
    new GradeModel({ threshold: 100, grade: `S+`, title: `Drop Deity`, description: `Perfection incarnate!`, emoji: `🏆` }),
    new GradeModel({ threshold: 95, grade: `S`, title: `Drop Dynamo`, description: `Flawless timing — unstoppable precision!`, emoji: `🎯` }),
    new GradeModel({ threshold: 90, grade: `A+`, title: `Stop Sage`, description: `Elite-level reaction speed`, emoji: `🧘` }),
    new GradeModel({ threshold: 85, grade: `A`, title: `Zone Zealot`, description: `Consistently landing in the sweet spot`, emoji: `🔍` }),
    new GradeModel({ threshold: 80, grade: `B+`, title: `Rapid Reacter`, description: `Fast and reliable, on your way`, emoji: `⚡` }),
    new GradeModel({ threshold: 75, grade: `B`, title: `Decent Dropper`, description: `Solid control, occasional missteps`, emoji: `📚` }),
    new GradeModel({ threshold: 70, grade: `C+`, title: `Late Bloomer`, description: `Slow reactions but improving`, emoji: `🌱` }),
    new GradeModel({ threshold: 65, grade: `C`, title: `Hesitant Handler`, description: `Second-guessing leads to misses`, emoji: `🤷` }),
    new GradeModel({ threshold: 60, grade: `D+`, title: `Silly Stopper`, description: `Mostly missing the timing`, emoji: `🫳` }),
    new GradeModel({ threshold: 55, grade: `D`, title: `Chaotic Clicker`, description: `More luck than skill`, emoji: `🎲` }),
    new GradeModel({ threshold: 0, grade: `F`, title: `Miserable Masher`, description: `Drop Disaster!`, emoji: `💥` }),
  ];

  // prettier-ignore
  const difficulties = [
    new DifficultyModel({ name: 'Easy', height: 20, speed: 900, }),
    new DifficultyModel({ name: 'Normal', height: 12, width: 15, speed: 1800, selected: true, }),
    new DifficultyModel({ name: 'Hard', height: 8, width: 10, speed: 3600, }),
    new DifficultyModel({ name: 'Ultra', height: 4, width: 5, speed: 4000, }),
  ];

  var campaigns = [
    new CampaignModel({
      name: `Tutorial`,
      subtitle: `Learn the basics of drop 'n stop`,
      selected: true,
      isTutorial: true,
      locked: false,
      sets: [
        new SetModel({
          id: 0,
          name: `The basics`,
          description: `Your goal is to stop the puck within the dropzone`,
          difficulty: difficulties[0],
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 215, ty: 50, th: 190, showPuck: true, name: `you control gravity`, description: `the puck falls when you press/hold the "drop" button` }),
            new StageModel({ kx: 0, ty: 200, th: 40, showPuck: true, name: `you get 3 chances`, description: `each miss lowers the dropzone's value` }),
            new StageModel({ kx: 420, ty: 100, th: 120, name: `hidden puck!`, description: `sometimes the puck won't appear unless you are pressing the "drop" button` }),
            new StageModel({ kx: 420, ty: 220, th: 170, showPuck: true, hideTarget: true, name: `hidden dropzone!`, description: `sometimes the dropzone won't appear unless you are pressing the "drop" button` }),
          ],
        }),
      ],
    }),
    new CampaignModel({
      id: 1,
      name: 'Zen Mode',
      subtitle: `Master your stops with endless drops`,
      isEndless: true,
      locked: false,
    }),

    new CampaignModel({
      id: 2,
      name: `Precision Primer`,
      subtitle: `Ease in—then dodge the dissonance`,
      selected: true,
      isTutorial: false,
      locked: false,
      sets: [
        new SetModel({
          name: `Steady Starts`,
          description: `Targets appear in a comfort zone. Find the beat.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 200, ty: 250, th: 100 }),
            new StageModel({ kx: 260, ty: 260, th: 105 }),
            new StageModel({ kx: 180, ty: 240, th: 96 }),
            new StageModel({ kx: 220, ty: 255, th: 92 }),
            new StageModel({ kx: 240, ty: 245, th: 98 }),
          ],
        }),
        new SetModel({
          name: `Pulse Shift`,
          description: `Minor waves in vertical spacing challenge your groove.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 210, ty: 230, th: 90 }),
            new StageModel({ kx: 190, ty: 270, th: 108 }),
            new StageModel({ kx: 220, ty: 260, th: 95 }),
            new StageModel({ kx: 240, ty: 235, th: 85 }),
            new StageModel({ kx: 200, ty: 275, th: 100 }),
            new StageModel({ kx: 230, ty: 250, th: 92 }),
          ],
        }),
        new SetModel({
          name: `Spacing Stretch`,
          description: `Target position creeps wider. Keep your timing tight.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 180, ty: 220, th: 114 }),
            new StageModel({ kx: 210, ty: 290, th: 86 }),
            new StageModel({ kx: 160, ty: 200, th: 90 }),
            new StageModel({ kx: 230, ty: 310, th: 105 }),
            new StageModel({ kx: 200, ty: 190, th: 92 }),
            new StageModel({ kx: 210, ty: 280, th: 110 }),
            new StageModel({ kx: 240, ty: 260, th: 88 }),
          ],
        }),
        new SetModel({
          name: `Anchor Break`,
          description: `Rhythm drifts as placements move high and low.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 160, ty: 180, th: 78 }),
            new StageModel({ kx: 170, ty: 300, th: 120 }),
            new StageModel({ kx: 220, ty: 140, th: 95 }),
            new StageModel({ kx: 190, ty: 350, th: 100 }),
            new StageModel({ kx: 240, ty: 170, th: 92 }),
            new StageModel({ kx: 230, ty: 330, th: 108 }),
            new StageModel({ kx: 200, ty: 120, th: 85 }),
            new StageModel({ kx: 180, ty: 375, th: 105 }),
          ],
        }),
        new SetModel({
          name: `Altitude Flux`,
          description: `Big swings in position. Focus or fumble.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 150, ty: 90, th: 88 }),
            new StageModel({ kx: 180, ty: 410, th: 112 }),
            new StageModel({ kx: 160, ty: 60, th: 94 }),
            new StageModel({ kx: 200, ty: 430, th: 108 }),
            new StageModel({ kx: 180, ty: 100, th: 90 }),
            new StageModel({ kx: 220, ty: 360, th: 120 }),
            new StageModel({ kx: 200, ty: 70, th: 84 }),
            new StageModel({ kx: 210, ty: 400, th: 110 }),
            new StageModel({ kx: 230, ty: 95, th: 92 }),
          ],
        }),
        new SetModel({
          name: `Soft Falls, Hard Landings`,
          description: `The finale arrives — narrow, fast, and high.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 210, ty: 250, th: 110 }),
            new StageModel({ kx: 210, ty: 100, th: 92 }),
            new StageModel({ kx: 210, ty: 270, th: 66 }),
            new StageModel({ kx: 210, ty: 60, th: 88 }),
            new StageModel({ kx: 210, ty: 310, th: 42 }),
            new StageModel({ kx: 210, ty: 140, th: 102 }),
            new StageModel({ kx: 210, ty: 330, th: 75 }),
            new StageModel({ kx: 210, ty: 73, th: 64 }),
            new StageModel({ kx: 210, ty: 142, th: 40 }),
            new StageModel({ kx: 210, ty: 250, th: 24 })],
        }),
      ],
    }),
    new CampaignModel({
      id: 3,
      name: `Edge of Expectation`,
      subtitle: `Precision alone won’t save you now`,
      selected: false,
      isTutorial: false,
      locked: false,
      sets: [
        new SetModel({
          name: `Measured Drops`,
          description: `Shrink the height, swing the beat.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 200, ty: 250, th: 120 }),
            new StageModel({ kx: 200, ty: 230, th: 112 }),
            new StageModel({ kx: 200, ty: 270, th: 105 }),
            new StageModel({ kx: 200, ty: 220, th: 98 }),
            new StageModel({ kx: 200, ty: 280, th: 90 }),
            new StageModel({ kx: 200, ty: 210, th: 84 }),
            new StageModel({ kx: 200, ty: 290, th: 78 }),
            new StageModel({ kx: 200, ty: 200, th: 74 }),
            new StageModel({ kx: 200, ty: 300, th: 70 }),
            new StageModel({ kx: 200, ty: 250, th: 76 }),
          ],
        }),
        new SetModel({
          name: `Slack Breaker`,
          description: `The safety net frays. Now, reposition faster.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 180, ty: 160, th: 110 }),
            new StageModel({ kx: 230, ty: 340, th: 88 }),
            new StageModel({ kx: 170, ty: 130, th: 100 }),
            new StageModel({ kx: 220, ty: 390, th: 84 }),
            new StageModel({ kx: 190, ty: 90, th: 95 }),
            new StageModel({ kx: 200, ty: 410, th: 80 }),
            new StageModel({ kx: 210, ty: 70, th: 78 }),
            new StageModel({ kx: 200, ty: 360, th: 82 }),
            new StageModel({ kx: 190, ty: 120, th: 86 }),
            new StageModel({ kx: 210, ty: 400, th: 74 }),
          ],
        }),
        new SetModel({
          name: `No Floor, No Ceiling`,
          description: `You’ve got the range—now use it.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 180, ty: 50, th: 88 }),
            new StageModel({ kx: 220, ty: 450, th: 70 }),
            new StageModel({ kx: 170, ty: 90, th: 84 }),
            new StageModel({ kx: 230, ty: 410, th: 74 }),
            new StageModel({ kx: 160, ty: 100, th: 68 }),
            new StageModel({ kx: 240, ty: 400, th: 66 }),
            new StageModel({ kx: 200, ty: 130, th: 72 }),
            new StageModel({ kx: 210, ty: 390, th: 60 }),
            new StageModel({ kx: 190, ty: 150, th: 64 }),
            new StageModel({ kx: 220, ty: 370, th: 58 }),
          ],
        }),
        new SetModel({
          name: `Thin Air`,
          description: `Small targets. Big control.`,
          difficulty: difficulties[0],
          showPuck: true,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 200, ty: 250, th: 38 }),
            new StageModel({ kx: 180, ty: 120, th: 32 }),
            new StageModel({ kx: 220, ty: 330, th: 40 }),
            new StageModel({ kx: 170, ty: 90, th: 28 }),
            new StageModel({ kx: 230, ty: 375, th: 36 }),
            new StageModel({ kx: 160, ty: 160, th: 30 }),
            new StageModel({ kx: 240, ty: 270, th: 34 }),
            new StageModel({ kx: 190, ty: 100, th: 26 }),
            new StageModel({ kx: 210, ty: 290, th: 22 }),
            new StageModel({ kx: 200, ty: 250, th: 24 }),
          ],
        }),
        new SetModel({
          name: `Now You See It`,
          description: `Hidden puck stages creep in. Trust the beat.`,
          difficulty: difficulties[0],
          showPuck: true, // overridden at stage level
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 200, ty: 130, th: 88 }),
            new StageModel({ kx: 210, ty: 340, th: 76 }),
            new StageModel({ kx: 200, ty: 110, th: 70, showPuck: false }),
            new StageModel({ kx: 220, ty: 360, th: 72 }),
            new StageModel({ kx: 190, ty: 100, th: 66 }),
            new StageModel({ kx: 230, ty: 390, th: 60 }),
            new StageModel({ kx: 180, ty: 90, th: 58, showPuck: false }),
            new StageModel({ kx: 240, ty: 410, th: 54 }),
            new StageModel({ kx: 200, ty: 120, th: 50 }),
            new StageModel({ kx: 220, ty: 370, th: 44 }),
          ],
        }),
        new SetModel({
          name: `Blind Landing`,
          description: `No puck. Little time. Nail the drop.`,
          difficulty: difficulties[0],
          showPuck: false,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 200, ty: 150, th: 70 }),
            new StageModel({ kx: 190, ty: 360, th: 66 }),
            new StageModel({ kx: 210, ty: 130, th: 60 }),
            new StageModel({ kx: 180, ty: 390, th: 56 }),
            new StageModel({ kx: 220, ty: 110, th: 52 }),
            new StageModel({ kx: 170, ty: 410, th: 48 }),
            new StageModel({ kx: 230, ty: 90, th: 42 }),
            new StageModel({ kx: 160, ty: 430, th: 38 }),
            new StageModel({ kx: 240, ty: 70, th: 35, difficulty: difficulties[1] }),
            new StageModel({ kx: 150, ty: 450, th: 30, difficulty: difficulties[1] }),
          ],
        }),
      ],
    }),
    new CampaignModel({
      id: 4,
      name: `Sight Unseen`,
      subtitle: `When rhythm and instinct collide`,
      selected: false,
      isTutorial: false,
      locked: false,
      sets: [
        new SetModel({
          name: `Peripheral Vision`,
          description: `The puck’s hidden, but the target guides you.`,
          difficulty: difficulties[0],
          showPuck: false,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 200, ty: 240, th: 110 }),
            new StageModel({ kx: 210, ty: 260, th: 100 }),
            new StageModel({ kx: 190, ty: 250, th: 90 }),
            new StageModel({ kx: 220, ty: 240, th: 84 }),
            new StageModel({ kx: 200, ty: 110, th: 78, hideTarget: true }),
            new StageModel({ kx: 210, ty: 280, th: 92 }),
            new StageModel({ kx: 180, ty: 130, th: 80 }),
            new StageModel({ kx: 230, ty: 270, th: 86 }),
            new StageModel({ kx: 190, ty: 360, th: 94 }),
            new StageModel({ kx: 220, ty: 250, th: 88 }),
          ],
        }),
        new SetModel({
          name: `On Faith`,
          description: `The world dims a bit more. Start listening deeper.`,
          difficulty: difficulties[0],
          showPuck: false,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 210, ty: 100, th: 84 }),
            new StageModel({ kx: 190, ty: 320, th: 76, hideTarget: true }),
            new StageModel({ kx: 220, ty: 90, th: 70 }),
            new StageModel({ kx: 180, ty: 360, th: 92 }),
            new StageModel({ kx: 230, ty: 120, th: 88, hideTarget: true }),
            new StageModel({ kx: 170, ty: 390, th: 94 }),
            new StageModel({ kx: 240, ty: 100, th: 80, hideTarget: true }),
            new StageModel({ kx: 160, ty: 430, th: 78 }),
            new StageModel({ kx: 200, ty: 250, th: 90, hideTarget: true }),
            new StageModel({ kx: 210, ty: 150, th: 86 }),
          ],
        }),
        new SetModel({
          name: `Feeling For Form`,
          description: `Confidence meets uncertainty.`,
          difficulty: difficulties[0],
          showPuck: false,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 180, ty: 130, th: 86, hideTarget: true }),
            new StageModel({ kx: 220, ty: 370, th: 78, hideTarget: true }),
            new StageModel({ kx: 170, ty: 160, th: 74 }),
            new StageModel({ kx: 230, ty: 340, th: 68, hideTarget: true }),
            new StageModel({ kx: 160, ty: 190, th: 64 }),
            new StageModel({ kx: 240, ty: 310, th: 60, hideTarget: true }),
            new StageModel({ kx: 200, ty: 100, th: 70 }),
            new StageModel({ kx: 210, ty: 400, th: 66, hideTarget: true }),
            new StageModel({ kx: 190, ty: 90, th: 60, hideTarget: true }),
            new StageModel({ kx: 220, ty: 370, th: 62 }),
          ],
        }),
        new SetModel({
          name: `Vanishing Points`,
          description: `Timing's tighter. Half the targets disappear.`,
          difficulty: difficulties[1],
          showPuck: false,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 200, ty: 110, th: 60 }),
            new StageModel({ kx: 210, ty: 330, th: 52, hideTarget: true }),
            new StageModel({ kx: 190, ty: 90, th: 46 }),
            new StageModel({ kx: 220, ty: 370, th: 40, hideTarget: true }),
            new StageModel({ kx: 180, ty: 120, th: 44 }),
            new StageModel({ kx: 230, ty: 360, th: 38, hideTarget: true }),
            new StageModel({ kx: 170, ty: 130, th: 36 }),
            new StageModel({ kx: 240, ty: 390, th: 34, hideTarget: true }),
            new StageModel({ kx: 200, ty: 150, th: 30 }),
            new StageModel({ kx: 210, ty: 310, th: 28, hideTarget: true }),
          ],
        }),
        new SetModel({
          name: `Hidden Geometry`,
          description: `You're flying half-blind now.`,
          difficulty: difficulties[1],
          showPuck: false,
          hideTarget: false,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 180, ty: 120, th: 54, hideTarget: true }),
            new StageModel({ kx: 220, ty: 360, th: 42 }),
            new StageModel({ kx: 170, ty: 140, th: 38, hideTarget: true }),
            new StageModel({ kx: 230, ty: 340, th: 34 }),
            new StageModel({ kx: 160, ty: 160, th: 30, hideTarget: true }),
            new StageModel({ kx: 240, ty: 320, th: 28 }),
            new StageModel({ kx: 200, ty: 180, th: 36, hideTarget: true }),
            new StageModel({ kx: 210, ty: 300, th: 32 }),
            new StageModel({ kx: 190, ty: 200, th: 26, hideTarget: true }),
            new StageModel({ kx: 220, ty: 280, th: 24 }),
          ],
        }),
        new SetModel({
          name: `Lucid Guesswork`,
          description: `Your intuition now does the aiming.`,
          difficulty: difficulties[1],
          showPuck: false,
          hideTarget: true,
          locked: false,
          // prettier-ignore
          stages: [
            new StageModel({ kx: 200, ty: 150, th: 66 }),
            new StageModel({ kx: 190, ty: 360, th: 60, difficulty: difficulties[0] }),
            new StageModel({ kx: 210, ty: 130, th: 54 }),
            new StageModel({ kx: 180, ty: 390, th: 52 }),
            new StageModel({ kx: 220, ty: 110, th: 46 }),
            new StageModel({ kx: 170, ty: 410, th: 44 }),
            new StageModel({ kx: 230, ty: 90, th: 42 }),
            new StageModel({ kx: 160, ty: 430, th: 38 }),
            new StageModel({ kx: 240, ty: 70, th: 36, difficulty: difficulties[0] }),
            new StageModel({ kx: 150, ty: 450, th: 32 }),
          ],
        }),
      ],
    }),
  ];

  return {
    grades,
    difficulties,
    campaigns,
    DifficultyModel,
    GradeModel,
    StageModel,
    SetModel,
    CampaignModel,
    ResultModel,
    YesNoModel,
  };
}
